name: 2nd-workflow
on:
  push:
    branches:
      - "main"
jobs:
  second-job:
    - name: 2nd-job
      runs-on: ubuntu-latest
      steps:
        - name: checkout step
          uses: actions/checkout@v4
        - name: run maven
          run: mvn clean package
          shell: bash