name: docker build workflow
on:
    push:
        branches:
            - "main"
jobs:
    build-image:
        name: build-dockerimage
        runs-on: ubuntu-latest
        steps:
            - name: checkout step
              uses: actions/checkout@v4

            - name: step up dockerbuild
              uses: docker/setup-buildx-action@v3

            - name: login to dockerhub
              uses: docker/login-action@v3
              with:
               username: ${{  vars.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: build and push the image
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: mahmoudabdelatif/gh-actions-js:${{ github.sha }} 

              
            

      